#! /bin/bash

# =============================================================================
#
# cernvm-preconditions
# --------------------
#
# This script contains each of the CernVM Release Testing precondition
# tests, which are required preconditions that must pass for the results 
# of test cases to be accurate. The precondition tests have a simple
# interface to execute each test and each test returns either a success or 
# failure, (0 or 1)
#
# More complex precondition tests can be created by combining other 
# precondition tests as prerequisites for a precondition test
#
# =============================================================================

# GENERIC PRECONDITION TESTS
# --------------------------

# Precondition Test - Verify that a file exists
# @param $1 - The location and name of the file
verify_file_exists()
{
	file_exists $1
	
	return $?
}

# Precondition Test - Verify the hash of a file
# @param $1 - The location and name of the file
verify_hash()
{
	return 0
}

# Precondition Test - Download and extract the CernVM image, returns the location 
#					  of the extracted cernvm image file
# @param $1 - The CernVM image download url
# @param $2 - The CernVM image hash url
# @param $3 - The name of the log file
download_extract()
{
	RESULT=1
	# This is specific to the cernvm website which doesn't give the actual location
	FILENAME=$(filename_from_url http://rbuilder.cern.ch/downloadImage?fileId=1719)
	IMAGE_FOLDER=""
	IMAGE_LOCATION=""

	# Precondition - verify file has not already been downloaded
	if verify_file_exists ${FILENAME} ; test "$?" -eq 1
	then
		# Download the image
		wget --verbose $1 > $3 2>&1
		echo $?
		# If download succeeded extract file		
		if test "$?" -eq 0 && verify_file_exists ${FILENAME} ; test "$?" -eq 0
		then
			echo "file downloaded, extracting"
			# Extract image into a subfolder of the root directory for CernVM images
			IMAGE_FOLDER=$(extract_file ${FILENAME} $IMAGES_DIR)
			
			echo ${IMAGE_FOLDER}
			# Verify extraction succeeded and folder exists
			if test "$?" -eq 0 && verify_file_exists ${IMAGE_FOLDER} ; test "$?" -eq 0
			then
				# Set the global setting for location of the image
				IMAGE_LOCATION=$(filename_from_ext ${IMAGE_FOLDER} hdd)
				echo ${IMAGE_LOCATION}
				RESULT=0
			fi
		fi			
	fi

	echo ${IMAGE_LOCATION}
	return $RESULT
}

# VIRTUAL MACHINE RELATED PRECONDITION TESTS
# ------------------------------------------

# Precondition Test - Verify that virtual machine NAT network is active and 
#					  set to autostart
# @param $1 - The virtual machine network name
verify_vm_net()
{
	RESULT=1

	# Verify that the network is set as active
	if vm_net_active $1 ; test "$?" -eq 0
	then
		# Verify that the network set as autostart
		if vm_net_autostart $1 ; test "$?" -eq 0
		then
			RESULT=0
		fi
	fi

	return $RESULT
}

# Precondition Test - Verify that the XML definition file provided is valid
# @param $1 - The virtual machine XML definition file
validate_def_xml()
{
	RESULT=1

	# Precondition - verify file exists
	if file_exists $1 ; test "$?" -eq 0
	then
		# Verify xml file is valid
		if xmllint --noout $1 ; test "$?" -eq 0
		then
			RESULT=0
		fi
	fi

	return $RESULT
}	
		
# Precondition Test - Verify that the mandatory configuration settings for the virtual
#					  machine XML definition file have been provided and are valid
# @param $1 - The virtual machine XML definition file
validate_def_settings()
{
	RESULT=1

	# Precondition - verify file exists
	# Precondition - verify xml file is valid
	if verify_file_exists $1 ; test "$?" -eq 0 \
	&& validate_def_xml $1 ; test "$?" -eq 0
	then
		# Check that mandatory settings are correct
		# Verify domain type from xml file, return failure if not valid type
		DOMAIN_TYPE=$(egrep -E "^<domain[[:space:]]*type='([a-zA-Z]+)'" $1 | sed -E \
					"s/.*type='([^']+)'.*/\\1/")
		case "$DOMAIN_TYPE" in
		"kvm")
		  ;;
		"vbox")
		  ;;
		"vmware")
		  ;;
		*)
		  return $RESULT
		  ;;
		esac

		# Verify that the name is set
		if egrep -q -E "^[[:space:]]*<name>.+</name>" $1 ; test "$?" -ne 0
		then
			# No virtual machine name set
			return $RESULT
		fi

		# Verify that the number of virtual cpus is set
		if egrep -q -E "^[[:space:]]*<vcpu>[0-9]{1}</vcpu>" $1 ; test "$?" -ne 0
		then
			# No vcpus set
			return $RESULT
		fi

		# Verify that the memory is set
		if egrep -q -E "^[[:space:]]*<memory>[0-9]+</memory>" $1 ; test "$?" -ne 0
		then
			# No memory set
			return $RESULT
		fi

		# Verify that the virtual machine image file is set and exists
		IMAGE_FILE=$(egrep -E "^[[:space:]]*<source file='(.*)'" $1 | sed -E "s/.*'([^']+)'.*/\\1/")
		if verify_file_exists $IMAGE_FILE ; test "$?" -ne 0
		then
			# Image file not set, or doesn't exist
			return $RESULT
		fi
	
		# All mandatory configuration settings for the virtual machine XML 
		# definition file have been provided and are valid
		RESULT=0
	fi

	return $RESULT
}

# Precondition Test - Verify that the hypervisor for the current virtual machine
#					  tested is accessible, set the hypervisor URI as a global variable
# @param $1 - The virtual machine XML definition file
verify_hypervisor()
{
	RESULT=1
	URI="test:///default"

	# Precondition - Validate the mandatory virtual machine settings for the hypervisor
	if validate_def_settings $1 ; test "$?" -eq 0
	then
		# Set the virsh URI for the virtual machine hypervisor
		DOMAIN_TYPE=$(egrep -E "^<domain[[:space:]]*type='([a-zA-Z]+)'" $1 | sed -E \
					"s/.*type='([^']+)'.*/\\1/")
		case "$DOMAIN_TYPE" in
		"kvm")
		  URI="qemu:///system"
		  ;;
		"vbox")
		  URI="vbox:///session"
		  ;;
		"vmware")
		  URI="vmwarews:///session"
		  ;;
		esac
	fi

	# If it is possible to connect to the hypervisor through virsh export URI
	if connect_virsh $URI ; test "$?" -eq 0
	then
		export "$URI"
		RESULT=0
	fi

	return $RESULT
}

# Precondition Test 2  - Create an XML definition file for the virtual machine based
#						 on the template XML definition file and settings defined and
#						 return the location of the final xml defintion file
# @param $1	- The template file to use
# @param $2 - The directory to save the final xml definition file in
create_def()
{
	RESULT=1
	TEMPLATE_FILE="$TEMPLATE_DIR/$1"
	DEFINITION_FILE=""
	
	# Precondition - Verify that the template file and destination directory exist
	if verify_file_exists $TEMPLATE_FILE ; test "$?" -eq 0 \
	&& verify_file_exists $2 ; test "$?" -eq 0
	then
		echo "success, creating file"
		# Copy template file to the directory specied
		cp -f $TEMPLATE_FILE $2
		
		# Set the definition file location
		DEFINITION_FILE="$2/$1"

		# Apply each virtual setting specified to create the final definition file
		# Set the only mandatory definition setting not specified in template
		if [ "$CERNVM_IMAGE" ]
		then
			# Set the location of the cernvm image file
			# Must use a different delimeter since variable is a path
			sed -i -E "s|<source file='.*'|<source file='$CERNVM_IMAGE'|" $DEFINITION_FILE
		fi
		
		# Set the following template setting overrides, if specified
		if [ "$VM_NAME" ]
		then
			# Override the default virtual machine name
			sed -i -E "s|<name>.*</name>|<name>$VM_NAME</name>|" $DEFINITION_FILE
		fi

		if [ "$VM_CPUS" ]
		then
			# Override the default number of cpus
			sed -i -E "s|<vcpu>.*</vcpu>|<vcpu>$VM_CPUS</vcpu>|" $DEFINITION_FILE
		fi

		if [ "$VM_MEMORY" ]
		then
			# Override the default amount of memory
			sed -i -E "s|<memory>.*</memory>|<memory>$VM_MEMORY</memory>|" \
			$DEFINITION_FILE
		fi

		if [ "$VM_NET" ]
		then
			# Override the default virtual network name
			sed -i -E "s|<source[[:space:]]*network='.*'\/>|<source network='$VM_NET'\/>|" 
			\ $DEFINITION_FILE
		fi

		if [ "$VM_VIDEO_MEMORY" ]
		then
			# Override the default amount of video memory
			sed -i -E "s|vram='.*'|vram='$VM_VIDEO_MEMORY'|" $DEFINITION_FILE
		fi

		RESULT=0
	fi
	
	echo $DEFINITION_FILE
	return $RESULT
}



# 	TODO CLEAN UP THE FOLLOWING PRECONDITON TESTS AND PLACE THEM IN THIS FILE
#	Precondition Test 2 - Verify that virtual machine domain has been created 
#						  from an xml file
#
#	Precondition Test 3 - Verify that virtual machine can be started
#
#	Precondition Test 4 - Verify that virtual machine has been stopped
#
#	Precondition Test 5 - Verify that the virtual has console support
#
#	Precondition Test 6 - Verify that virtual machine has web interface support
#
#	Precondition Test 7 - Verify that it is possible to login on web interface
