#! /bin/bash

# =============================================================================
#
# web-interface
# -----------------
#
# This script contains several  functions that provide an interface to
# the CernVM virtual machine web interface and return a success or failure, 
# which can be used to generate a TAP report.
#
# These functions can be utilized to create test cases in cernvm-testcases or 
# can be executed individually as precondition tests
#
# =============================================================================
